### PR TITLE
Chip Calculator: New UI for selecting number of blocks

### PR DESCRIPTION
**Pull request by johnchen902**
This image should be enough to explain this pull request:

### CODE REVIEW

**Comment by hycdes** [comment]
我觉得你这个提议不错，现在语言版本比较多，需要改三个页面，改好后将标注鸣谢列表

**Comment by johnchen902** [comment]
Well, I'm busy next week and won't have time to resolve the conflicts. You have to take over if you want it to land before April 8.

BTW actually my first language is Chinese. Should I reply in Chinese instead?

**Comment by hycdes** [comment]
沒關係，我把網頁改好，因為多語言以及後續代碼重構，有的部分處理衝突很麻煩，我自己改就行了。
感謝你的建議 :) ，我會在鳴謝列表裡標註，用你github暱稱標註可以嗎？

**Comment by johnchen902** [comment]
> 用你github暱稱標註可以嗎？

Affirmative

**Comment by johnchen902** [comment]
Apparently the change has been made, so I think I should close this.

BTW I hereby confirm I'm also the johnchen902 on NGA.

**Pull request closed without merging**
